Repository RM35/steel-chalk-asset, pull requests merged in 2022-06, with the labels that each got.

#13 ci: add ci and dockerfile
  .github/CODEOWNERS
  .github/workflows/docker-build-push.yaml
  dockerfile
  export_presets.cfg
Labels: enhancement

#21 Wparr/feature/ci
  .github/release.yml
Labels: PullRequest0021

#24 label PRs for generated release notes
  .github/workflows/ci.yaml
Labels: Semver-Minor

#30 feat: something
  GitVersion.yml
Labels: Semver-Minor, Semver-Major

#38 feature/probabilities
  project.godot
  unit/unit.gd
  unit/unit_data/unit_chicken.tres
  unit/unit_data/unit_friendly_cat.tres
  unit/unit_data/unit_lungs.tres
  unit/unit_data/unit_shield.tres
  unit/unit_data/unit_skull.tres
  unit/unit_stats.gd
  world/world.gd
  world/world.tscn
Labels: Semver-Minor
